/// Converts an HTML string (as generated by the Textual library's copy formatter)
/// into a Markdown string.
///
/// This is a rule-based converter scoped to the HTML that Textual emits for common
/// Markdown constructs: headings, paragraphs, bold, italic, inline code, fenced code
/// blocks, links, unordered/ordered lists, blockquotes, and horizontal rules.
public func htmlToMarkdown(_ html: String) -> String {
    let tokens = tokenizeHTML(html)
    var ctx = ConversionContext()
    for token in tokens {
        applyToken(token, to: &ctx)
    }
    return ctx.finalize()
}

// MARK: - Tokenizer

private enum HTMLToken {
    case text(String)
    case open(tag: String, attrs: [String: String])
    case close(tag: String)
    case selfClose(tag: String)
}

private func tokenizeHTML(_ html: String) -> [HTMLToken] {
    var tokens: [HTMLToken] = []
    var i = html.startIndex

    while i < html.endIndex {
        if html[i] == "<" {
            guard let end = html[i...].firstIndex(of: ">") else {
                tokens.append(.text(String(html[i...])))
                break
            }
            let raw = String(html[html.index(after: i)..<end])
            i = html.index(after: end)
            if raw.hasPrefix("!") { continue }   // doctype / comment
            tokens.append(parseHTMLTag(raw))
        } else {
            let start = i
            while i < html.endIndex && html[i] != "<" {
                i = html.index(after: i)
            }
            let text = String(html[start..<i])
            if !text.isEmpty { tokens.append(.text(text)) }
        }
    }
    return tokens
}

private func parseHTMLTag(_ raw: String) -> HTMLToken {
    let s = raw.trimmingCharacters(in: .whitespaces)
    let selfClosing = s.hasSuffix("/")
    let body = selfClosing ? String(s.dropLast()).trimmingCharacters(in: .whitespaces) : s

    if body.hasPrefix("/") {
        let tag = String(body.dropFirst())
            .components(separatedBy: .whitespaces).first!
            .lowercased()
        return .close(tag: tag)
    }

    var parts = splitRespectingQuotes(body)
    guard !parts.isEmpty else { return .text("") }
    let tag = parts.removeFirst().lowercased()
    let attrs = parseAttributes(parts.joined(separator: " "))

    return selfClosing ? .selfClose(tag: tag) : .open(tag: tag, attrs: attrs)
}

private func splitRespectingQuotes(_ s: String) -> [String] {
    var parts: [String] = []
    var current = ""
    var quote: Character? = nil
    for ch in s {
        if let q = quote {
            current.append(ch)
            if ch == q { quote = nil }
        } else if ch == "\"" || ch == "'" {
            quote = ch
            current.append(ch)
        } else if ch.isWhitespace {
            if !current.isEmpty { parts.append(current); current = "" }
        } else {
            current.append(ch)
        }
    }
    if !current.isEmpty { parts.append(current) }
    return parts
}

private func parseAttributes(_ s: String) -> [String: String] {
    var attrs: [String: String] = [:]
    // Matches: key, key=value, key="value", key='value'
    let pattern = #/(\w[\w-]*)(?:\s*=\s*(?:"([^"]*?)"|'([^']*?)'|([^\s>]*)))?/#
    for match in s.matches(of: pattern) {
        let key = String(match.output.1).lowercased()
        var value = ""
        if let v = match.output.2 { value = String(v) }
        else if let v = match.output.3 { value = String(v) }
        else if let v = match.output.4 { value = String(v) }
        attrs[key] = value
    }
    return attrs
}

// MARK: - Conversion context

private enum ListKind { case ul, ol }

private struct ConversionContext {
    var output = ""
    var pendingNewlines = 0

    // Block state
    var listStack: [ListKind] = []
    var listCounters: [Int] = []
    var blockquoteDepth = 0

    // Pre / code block state
    var inPre = false
    var preBuffer = ""

    // Inline state
    var boldDepth = 0
    var emDepth = 0
    var inInlineCode = false
    var pendingHref: String? = nil

    mutating func finalize() -> String {
        return output.trimmingCharacters(in: .newlines)
    }

    mutating func emit(_ text: String) {
        guard !text.isEmpty else { return }
        flushPendingNewlines()
        output += text
    }

    mutating func flushPendingNewlines() {
        guard pendingNewlines > 0 else { return }
        output += String(repeating: "\n", count: pendingNewlines)
        pendingNewlines = 0
    }

    mutating func requestNewlines(_ n: Int) {
        pendingNewlines = max(pendingNewlines, n)
    }

    var bqPrefix: String {
        blockquoteDepth > 0 ? String(repeating: "> ", count: blockquoteDepth) : ""
    }

    var listPrefix: String {
        guard let kind = listStack.last else { return "" }
        let indent = String(repeating: "  ", count: listStack.count - 1)
        switch kind {
        case .ul: return indent + "- "
        case .ol:
            let n = listCounters.last ?? 1
            return indent + "\(n). "
        }
    }
}

// MARK: - Token application

private func applyToken(_ token: HTMLToken, to ctx: inout ConversionContext) {
    switch token {
    case .text(let raw):
        applyText(raw, to: &ctx)
    case .selfClose(let tag):
        applySelfClose(tag: tag, to: &ctx)
    case .open(let tag, let attrs):
        applyOpen(tag: tag, attrs: attrs, to: &ctx)
    case .close(let tag):
        applyClose(tag: tag, to: &ctx)
    }
}

private func applyText(_ raw: String, to ctx: inout ConversionContext) {
    let decoded = decodeHTMLEntities(raw)
    if ctx.inPre {
        ctx.preBuffer += decoded
        return
    }
    // Collapse whitespace outside pre
    var text = decoded.replacingOccurrences(of: "\n", with: " ")
    while text.contains("  ") {
        text = text.replacingOccurrences(of: "  ", with: " ")
    }
    if text.trimmingCharacters(in: .whitespaces).isEmpty {
        // Whitespace-only text that originated from HTML newlines is structural
        // indentation and can be dropped. But a plain space (e.g. between two
        // inline tags, or from &nbsp;) should be kept when we are mid-line.
        if !decoded.contains("\n") && !ctx.output.hasSuffix("\n") && !ctx.output.isEmpty {
            ctx.emit(" ")
        }
        return
    }
    // Strip leading space at the beginning of a new line
    if ctx.output.hasSuffix("\n") || ctx.output.isEmpty {
        text = String(text.drop(while: { $0 == " " }))
    }
    ctx.emit(text)
}

private func applySelfClose(tag: String, to ctx: inout ConversionContext) {
    switch tag {
    case "br":
        if ctx.inPre { ctx.preBuffer += "\n" }
        else { ctx.requestNewlines(1) }
    case "hr":
        ctx.requestNewlines(2)
        ctx.emit(ctx.bqPrefix + "---")
        ctx.requestNewlines(2)
    default:
        break
    }
}

private func applyOpen(tag: String, attrs: [String: String], to ctx: inout ConversionContext) {
    switch tag {
    case "h1": startHeading("# ", ctx: &ctx)
    case "h2": startHeading("## ", ctx: &ctx)
    case "h3": startHeading("### ", ctx: &ctx)
    case "h4": startHeading("#### ", ctx: &ctx)
    case "h5": startHeading("##### ", ctx: &ctx)
    case "h6": startHeading("###### ", ctx: &ctx)

    case "p":
        ctx.requestNewlines(ctx.listStack.isEmpty ? 2 : 1)
        ctx.flushPendingNewlines()
        if !ctx.bqPrefix.isEmpty && ctx.listStack.isEmpty {
            ctx.output += ctx.bqPrefix
        }

    case "pre":
        ctx.inPre = true
        ctx.preBuffer = ""

    case "code" where ctx.inPre:
        break  // handled by pre

    case "code":
        ctx.inInlineCode = true
        ctx.emit("`")

    case "strong", "b":
        ctx.boldDepth += 1
        if ctx.boldDepth == 1 { ctx.emit("**") }

    case "em", "i":
        ctx.emDepth += 1
        if ctx.emDepth == 1 { ctx.emit("*") }

    case "s", "del", "strike":
        ctx.emit("~~")

    case "a":
        ctx.pendingHref = attrs["href"] ?? ""
        ctx.emit("[")

    case "ul":
        ctx.listStack.append(.ul)
        ctx.listCounters.append(0)
        if ctx.listStack.count == 1 { ctx.requestNewlines(2) }

    case "ol":
        ctx.listStack.append(.ol)
        ctx.listCounters.append(0)
        if ctx.listStack.count == 1 { ctx.requestNewlines(2) }

    case "li":
        ctx.requestNewlines(1)
        if case .ol = ctx.listStack.last {
            ctx.listCounters[ctx.listCounters.count - 1] += 1
        }
        ctx.flushPendingNewlines()
        ctx.output += ctx.listPrefix

    case "blockquote":
        ctx.blockquoteDepth += 1
        ctx.requestNewlines(2)

    default:
        break
    }
}

private func startHeading(_ marker: String, ctx: inout ConversionContext) {
    ctx.requestNewlines(2)
    ctx.flushPendingNewlines()
    ctx.output += ctx.bqPrefix + marker
}

private func applyClose(tag: String, to ctx: inout ConversionContext) {
    switch tag {
    case "h1", "h2", "h3", "h4", "h5", "h6":
        ctx.requestNewlines(2)

    case "p":
        ctx.requestNewlines(2)

    case "pre":
        let fence = ctx.bqPrefix + "```"
        ctx.requestNewlines(2)
        ctx.flushPendingNewlines()
        ctx.output += fence + "\n"
        ctx.output += ctx.preBuffer
        if !ctx.preBuffer.hasSuffix("\n") { ctx.output += "\n" }
        ctx.output += fence
        ctx.preBuffer = ""
        ctx.inPre = false
        ctx.requestNewlines(2)

    case "code" where ctx.inPre:
        break

    case "code":
        ctx.emit("`")
        ctx.inInlineCode = false

    case "strong", "b":
        if ctx.boldDepth == 1 { ctx.emit("**") }
        ctx.boldDepth = max(0, ctx.boldDepth - 1)

    case "em", "i":
        if ctx.emDepth == 1 { ctx.emit("*") }
        ctx.emDepth = max(0, ctx.emDepth - 1)

    case "s", "del", "strike":
        ctx.emit("~~")

    case "a":
        let href = ctx.pendingHref ?? ""
        ctx.emit("](\(href))")
        ctx.pendingHref = nil

    case "ul", "ol":
        if !ctx.listStack.isEmpty { ctx.listStack.removeLast() }
        if !ctx.listCounters.isEmpty { ctx.listCounters.removeLast() }
        if ctx.listStack.isEmpty { ctx.requestNewlines(2) }

    case "li":
        ctx.requestNewlines(1)

    case "blockquote":
        ctx.blockquoteDepth = max(0, ctx.blockquoteDepth - 1)
        ctx.requestNewlines(2)

    default:
        break
    }
}

// MARK: - HTML entity decoder

private func decodeHTMLEntities(_ s: String) -> String {
    var result = s
    let namedEntities: [(String, String)] = [
        ("&amp;",   "&"),
        ("&lt;",    "<"),
        ("&gt;",    ">"),
        ("&quot;",  "\""),
        ("&#39;",   "'"),
        ("&apos;",  "'"),
        ("&nbsp;",  " "),
        ("&#8203;", ""),
        ("&mdash;", "—"),
        ("&ndash;", "–"),
        ("&hellip;","…"),
    ]
    for (entity, replacement) in namedEntities {
        result = result.replacingOccurrences(of: entity, with: replacement)
    }
    // Numeric decimal entities &#NNN;
    var out = ""
    var idx = result.startIndex
    while idx < result.endIndex {
        if result[idx] == "&" && result[idx...].hasPrefix("&#") {
            if let semi = result[idx...].firstIndex(of: ";") {
                let numStr = String(result[result.index(idx, offsetBy: 2)..<semi])
                if let code = UInt32(numStr), let scalar = Unicode.Scalar(code) {
                    out += String(scalar)
                    idx = result.index(after: semi)
                    continue
                }
            }
        }
        out.append(result[idx])
        idx = result.index(after: idx)
    }
    return out
}
